### ISSUE TITLE
Composer create project fails with dependency resolution error 

### ISSUE THREAD

**Issue by charithar** [mezzio/mezzio-skeleton#46]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.8.0

#### Summary

Composer "create project" fails with dependency resolution error during the installation because one of packages does not support the minimum PHP version specified in the composer.json. This happened with PHP 7.3.25 and Composer 1.10.15.

#### Current behavior

After the configuration steps composer fails with following error.

> Your requirements could not be resolved to an installable set of packages.
>  Problem 1
>    - Installation request for chubbyphp/chubbyphp-container 2.0.0 -> satisfiable by chubbyphp/chubbyphp-container[2.0.0].
>    - chubbyphp/chubbyphp-container 2.0.0 requires php ^7.4|^8.0 -> your PHP version (7.3.25) does not satisfy that requirement.
>  Problem 2
>    - Installation request for chubbyphp/chubbyphp-laminas-config 1.2.1 -> satisfiable by chubbyphp/chubbyphp-laminas-config[1.2.1].
>    - chubbyphp/chubbyphp-laminas-config 1.2.1 requires php ^7.4|^8.0 -> your PHP version (7.3.25) does not satisfy that requirement.

#### How to reproduce

- Execute 'composer create-project mezzio/mezzio-skeleton mezzio' in PHP 7.3.25 environment
- Use default options for all the configuration steps. Different config options also show the same behavior

#### Expected behavior

Make the installer compatible with PHP 7.3.x

**Comment by Xerkus** [comment]
This is due to `composer.lock` file which is created for the 7.4. `composer create-project` is equivalent to `git clone` followed by `composer install`. 

@charithar You can checkout the skeleton app and then use `composer update` to make composer ignore lock file and resolve packages for your platform.

**Comment by charithar** [comment]
Thanks for the quick response. I have tried it out and it works.

**Comment by brayniverse** [comment]
I am getting the same error as issue #66  when I install using `create-project`. I'm aware that there is an ongoing discussion regarding the composer.lock file. However, I'm seeing some odd behaviour that I think may be related that you might not be aware of.

After using `create-project` and manually running `composer update` I tried to run `composer check` but because PHPCS is not available I get the following error:

```bash
> phpcs
'phpcs' is not recognized as an internal or external command,
operable program or batch file.
Script phpcs handling the cs-check event returned with error code 1
Script @cs-check was called via check
```

I assume this is because the installer didn't finish removing everything before it encountered the error mentioned in #66.

If this issue is not the correct place to report this bug then please tell me what you would rather I do.
